'use client'

import { useState, useCallback } from 'react'

interface Question {
  file: string
  question: string
  options: string[]
  correct: number
  explanation: string
}

const questions: Question[] = [
  {
    file: 'app/page.tsx',
    question: 'Where does this file run?',
    options: ['Browser only', 'Server (then sent to browser)', 'Build step only'],
    correct: 1,
    explanation: 'In Next.js App Router, page.tsx is a Server Component by default. It runs on the server and sends HTML to the browser.',
  },
  {
    file: 'components/Button.tsx',
    question: 'Why is this file special?',
    options: ['The framework discovers it by name', 'Another file imports it', 'It runs automatically on build'],
    correct: 1,
    explanation: 'Component files are ordinary modules — they only do something when imported by another file. No import, no effect.',
  },
  {
    file: 'app/layout.tsx',
    question: 'Why is this file special?',
    options: ['Another file imports it', 'The framework discovers it by name', 'It is a static asset'],
    correct: 1,
    explanation: 'layout.tsx is a convention file. Next.js looks for this specific filename and wraps pages with it automatically.',
  },
  {
    file: '.env.local',
    question: 'What bucket does this belong to?',
    options: ['Config & dependencies', 'Secrets', 'Generated output'],
    correct: 1,
    explanation: 'Files like .env.local hold secrets — API keys, database URLs, and values that should never be committed to git.',
  },
  {
    file: 'node_modules/',
    question: 'Is it safe to edit this?',
    options: ['Yes — it contains important project code', 'Only if you know what you\'re doing', 'No — it is generated output'],
    correct: 2,
    explanation: 'node_modules/ is generated by npm install. Editing it directly is patching the wrong layer — your changes will be overwritten.',
  },
  {
    file: 'package.json',
    question: 'What bucket does this belong to?',
    options: ['Routes & pages', 'Config & dependencies', 'Helpers & data'],
    correct: 1,
    explanation: 'package.json is the control panel — it tells you the framework, scripts, and dependencies. Open it first in any unfamiliar repo.',
  },
  {
    file: 'tailwind class: "hover:opacity-90"',
    question: 'What does the hover: prefix mean?',
    options: ['Apply on mobile only', 'Apply when the element is hovered', 'Apply during page load animation'],
    correct: 1,
    explanation: 'Tailwind prefixes like hover: and md: are conditions. hover: means "apply this style when the user hovers." It\'s CSS-in-markup.',
  },
  {
    file: 'app/blog/[slug]/page.tsx',
    question: 'What do the [brackets] mean?',
    options: ['The file is optional', 'It\'s a dynamic route parameter', 'It\'s a test file'],
    correct: 1,
    explanation: '[slug] is a dynamic route segment. It matches any URL like /blog/my-post and passes "my-post" as a parameter.',
  },
]

export default function RepoDecoder() {
  const [current, setCurrent] = useState(0)
  const [selected, setSelected] = useState<number | null>(null)
  const [score, setScore] = useState(0)
  const [finished, setFinished] = useState(false)
  const [showExplanation, setShowExplanation] = useState(false)

  const q = questions[current]

  const handleSelect = useCallback(
    (idx: number) => {
      if (selected !== null) return
      setSelected(idx)
      setShowExplanation(true)
      if (idx === q.correct) setScore((s) => s + 1)
    },
    [selected, q.correct]
  )

  const handleNext = useCallback(() => {
    if (current + 1 >= questions.length) {
      setFinished(true)
    } else {
      setCurrent((c) => c + 1)
      setSelected(null)
      setShowExplanation(false)
    }
  }, [current])

  const handleRestart = useCallback(() => {
    setCurrent(0)
    setSelected(null)
    setScore(0)
    setFinished(false)
    setShowExplanation(false)
  }, [])

  if (finished) {
    const pct = Math.round((score / questions.length) * 100)
    const message =
      pct === 100
        ? 'Perfect. You can read any repo.'
        : pct >= 75
        ? 'Strong instincts. The map is forming.'
        : pct >= 50
        ? 'Good start. Re-read the three questions framework above.'
        : 'Keep going. The patterns click faster than you think.'

    return (
      <div
        className="my-8 rounded-lg border p-6 sm:p-8"
        style={{ borderColor: 'var(--border-strong)', background: 'var(--bg-warm)' }}
      >
        <div className="text-center">
          <p
            className="font-mono text-xs font-medium uppercase tracking-widest"
            style={{ color: 'var(--accent)' }}
          >
            Repo Decoder — Results
          </p>
          <p
            className="mt-4 font-display text-4xl font-normal"
            style={{ color: 'var(--fg)' }}
          >
            {score}/{questions.length}
          </p>
          <p className="mt-2 text-sm" style={{ color: 'var(--fg-muted)' }}>
            {message}
          </p>
          <button
            onClick={handleRestart}
            className="btn-ghost mt-6"
          >
            Try again
          </button>
        </div>
      </div>
    )
  }

  return (
    <div
      className="my-8 rounded-lg border p-6 sm:p-8"
      style={{ borderColor: 'var(--border-strong)', background: 'var(--bg-warm)' }}
    >
      {/* Header */}
      <div className="mb-5 flex items-center justify-between">
        <p
          className="font-mono text-xs font-medium uppercase tracking-widest"
          style={{ color: 'var(--accent)' }}
        >
          Repo Decoder
        </p>
        <p className="text-xs" style={{ color: 'var(--fg-subtle)' }}>
          {current + 1} / {questions.length}
        </p>
      </div>

      {/* Progress bar */}
      <div
        className="mb-6 h-1 w-full overflow-hidden rounded-full"
        style={{ background: 'var(--border)' }}
      >
        <div
          className="h-full rounded-full transition-all duration-300"
          style={{
            width: `${((current + (selected !== null ? 1 : 0)) / questions.length) * 100}%`,
            background: 'var(--accent)',
          }}
        />
      </div>

      {/* File label */}
      <div
        className="mb-2 inline-block rounded px-2.5 py-1 font-mono text-sm"
        style={{ background: 'var(--accent-light)', color: 'var(--accent)' }}
      >
        {q.file}
      </div>

      {/* Question */}
      <p className="mb-4 text-base font-medium" style={{ color: 'var(--fg)' }}>
        {q.question}
      </p>

      {/* Options */}
      <div className="space-y-2">
        {q.options.map((opt, i) => {
          let borderColor = 'var(--border-strong)'
          let bg = 'transparent'
          if (selected !== null) {
            if (i === q.correct) {
              borderColor = '#16a34a'
              bg = 'rgba(22, 163, 74, 0.08)'
            } else if (i === selected && i !== q.correct) {
              borderColor = '#dc2626'
              bg = 'rgba(220, 38, 38, 0.06)'
            }
          }

          return (
            <button
              key={i}
              onClick={() => handleSelect(i)}
              disabled={selected !== null}
              className="w-full rounded-md border px-4 py-3 text-left text-sm transition-all"
              style={{
                borderColor,
                background: bg,
                color: 'var(--fg)',
                cursor: selected !== null ? 'default' : 'pointer',
                opacity: selected !== null && i !== selected && i !== q.correct ? 0.5 : 1,
              }}
            >
              {opt}
            </button>
          )
        })}
      </div>

      {/* Explanation */}
      {showExplanation && (
        <div className="mt-4">
          <p className="text-sm leading-relaxed" style={{ color: 'var(--fg-muted)' }}>
            {q.explanation}
          </p>
          <button
            onClick={handleNext}
            className="btn-primary mt-4"
            style={{ fontSize: '0.8rem', padding: '0.5rem 1.25rem' }}
          >
            {current + 1 >= questions.length ? 'See results' : 'Next question'}
            <svg width="12" height="12" viewBox="0 0 12 12" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round">
              <line x1="2" y1="6" x2="10" y2="6" />
              <polyline points="6.5 2.5 10 6 6.5 9.5" />
            </svg>
          </button>
        </div>
      )}
    </div>
  )
}
